# Generated by Django 6.0.4 on 2026-05-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_product',
            name='product_brand',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='add_product',
            name='product_colour',
            field=models.CharField(default=''),
        ),
    ]
